"""Native localhost bench for the existing two-node media-plane runtime."""

from __future__ import annotations

from dataclasses import dataclass, field
import json
import os
from pathlib import Path
import socket
import subprocess
import sys
import time
from typing import Any
from urllib.parse import urlparse

import yaml


DEFAULT_GENERATED_DIR = Path("configs/runs/local/generated")
DEFAULT_LOGS_DIR = Path("runs/local-two-node")
DEFAULT_ACTIVE_IDS = {
    "cr01_cr02_bench_v2": ["person", "helmet", "vest", "bare_head"],
    "cr01_cr02_v2_short": ["person", "helmet", "vest"],
}
SOURCE_REFS = {
    "bench-val": "bench_v2_val",
    "bench-test": "bench_v2_test",
    "demo": "demo_v2",
}
PROMPTS_BY_SOURCE = {
    "bench-val": "cr01_cr02_bench_v2",
    "bench-test": "cr01_cr02_bench_v2",
    "demo": "cr01_cr02_v2_short",
    "video": "cr01_cr02_v2_short",
    "ezviz": "cr01_cr02_v2_short",
}


@dataclass(frozen=True)
class LocalTwoNodeOptions:
    source: str
    video: Path | None = None
    rtsp_url: str | None = None
    codec: str = "jpeg"
    jpeg_quality: int = 90
    payload_format: str = "uint8_rgb"
    max_units: int | None = None
    device: str = "cuda:0"
    model_ref: str = "yoloe/yoloe-26s"
    prompts_ref: str | None = None
    save_previews: bool = False
    preview_max: int = 20
    generated_dir: Path = DEFAULT_GENERATED_DIR
    logs_dir: Path = DEFAULT_LOGS_DIR
    outputs_base_dir: Path = Path("runs")
    skip_probe: bool = False
    port_base: int | None = None
    startup_timeout_s: float = 10.0


def _require_supported_source(source: str) -> None:
    supported = {*SOURCE_REFS, "video", "ezviz"}
    if source not in supported:
        choices = ", ".join(sorted(supported))
        raise ValueError(f"--source debe ser uno de: {choices}")


def resolve_source(options: LocalTwoNodeOptions) -> dict[str, Any]:
    """Resolve a user-facing source profile into a run-config source section."""
    _require_supported_source(options.source)
    if options.source in SOURCE_REFS:
        return {"ref": SOURCE_REFS[options.source]}
    if options.source == "video":
        if options.video is None:
            raise ValueError("--source video requiere --video")
        return {"type": "video_file", "path": str(options.video)}
    rtsp_url = options.rtsp_url or os.environ.get("EZVIZ_RTSP_URL")
    if not rtsp_url:
        raise ValueError("--source ezviz requiere --rtsp-url o EZVIZ_RTSP_URL")
    return {
        "type": "rtsp",
        "path": rtsp_url,
        "url": rtsp_url,
        "reconnect_retries": 5,
        "reconnect_delay_ms": 1000,
    }


def resolve_prompts_ref(options: LocalTwoNodeOptions) -> str:
    """Return the prompt set reference for the selected source."""
    if options.prompts_ref:
        return options.prompts_ref
    _require_supported_source(options.source)
    return PROMPTS_BY_SOURCE[options.source]


def build_run_config(
    options: LocalTwoNodeOptions,
    *,
    endpoint: str,
    heartbeat_endpoint: str,
) -> dict[str, Any]:
    """Build the YAML-compatible run config used by both localhost nodes."""
    prompts_ref = resolve_prompts_ref(options)
    raw: dict[str, Any] = {
        "run": {
            "scenario": "EBE",
            "name": f"local_two_node_{options.source.replace('-', '_')}",
            "description": "Native localhost two-node bench generated by run-two-node-local.",
        },
        "source": resolve_source(options),
        "model": {"ref": options.model_ref, "device": options.device},
        "prompts": {
            "ref": prompts_ref,
            "active_ids": DEFAULT_ACTIVE_IDS.get(prompts_ref, ["person", "helmet", "vest"]),
        },
        "topology": {"mode": "two_node"},
        "transport": {
            "backend": "network",
            "endpoint": endpoint,
            "heartbeat_endpoint": heartbeat_endpoint,
            "payload_format": options.payload_format,
            "compression": {"codec": options.codec, "quality": options.jpeg_quality},
        },
        "outputs": {
            "run_dir": str(options.outputs_base_dir),
            "base_dir": str(options.outputs_base_dir),
            "save_previews": options.save_previews,
            "preview_max": options.preview_max,
        },
    }
    if options.max_units is not None:
        raw["run"]["max_units"] = options.max_units
    return raw


def write_generated_config(raw: dict[str, Any], generated_dir: Path, *, stem: str) -> Path:
    """Write a generated local run config and return its path."""
    generated_dir.mkdir(parents=True, exist_ok=True)
    path = generated_dir / f"{stem}.yaml"
    path.write_text(yaml.safe_dump(raw, sort_keys=False), encoding="utf-8")
    return path


def unused_tcp_endpoint() -> str:
    """Return a loopback TCP endpoint string for ZeroMQ."""
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
        sock.bind(("127.0.0.1", 0))
        port = sock.getsockname()[1]
    return f"tcp://127.0.0.1:{port}"


@dataclass(frozen=True)
class LocalTwoNodeResult:
    config_path: Path
    logs_dir: Path
    node_a_log: Path
    node_b_log: Path
    run_dir: Path | None
    node_a_returncode: int | None
    node_b_returncode: int | None
    summary: dict[str, Any] = field(default_factory=dict)
    warnings: list[str] = field(default_factory=list)

    @property
    def ok(self) -> bool:
        return self.node_a_returncode == 0 and self.node_b_returncode == 0

    @property
    def failure_reason(self) -> str:
        if self.ok:
            return ""
        if self.node_b_returncode not in (0, None):
            return f"Nodo B exited with code {self.node_b_returncode}"
        if self.node_a_returncode not in (0, None):
            return f"Nodo A exited with code {self.node_a_returncode}"
        return "Two-node local run did not complete"


def _endpoint_host_port(endpoint: str) -> tuple[str, int]:
    parsed = urlparse(endpoint)
    if parsed.scheme != "tcp" or parsed.hostname is None or parsed.port is None:
        raise ValueError(f"Solo endpoints tcp://host:port son soportados: {endpoint}")
    return parsed.hostname, parsed.port


def wait_for_tcp_endpoint(endpoint: str, *, timeout_s: float) -> bool:
    """Wait until a TCP endpoint accepts connections."""
    host, port = _endpoint_host_port(endpoint)
    deadline = time.monotonic() + timeout_s
    while time.monotonic() < deadline:
        try:
            with socket.create_connection((host, port), timeout=0.2):
                return True
        except OSError:
            time.sleep(0.05)
    return False


def scan_log_warnings(log_path: Path) -> list[str]:
    """Return warning/error lines from a node log."""
    if not log_path.exists():
        return []
    matches: list[str] = []
    for line in log_path.read_text(encoding="utf-8", errors="replace").splitlines():
        lowered = line.lower()
        if "warning" in lowered or "error" in lowered or "traceback" in lowered:
            matches.append(line)
    return matches


def collect_run_summary(run_dir: Path | None) -> dict[str, Any]:
    """Read summary.json and count errors.jsonl lines from a completed run."""
    if run_dir is None:
        return {}
    summary_path = run_dir / "summary.json"
    if not summary_path.exists():
        return {}
    summary = json.loads(summary_path.read_text(encoding="utf-8"))
    errors_path = run_dir / "errors.jsonl"
    summary["errors_count"] = (
        len(errors_path.read_text(encoding="utf-8").splitlines())
        if errors_path.exists()
        else 0
    )
    return summary


def _command_for_node(node: str, config_path: Path) -> list[str]:
    command = "run-producer" if node == "a" else "run-consumer"
    return [sys.executable, "-m", "eovrt_media.cli", command, "--config", str(config_path)]


def _subprocess_env() -> dict[str, str]:
    env = os.environ.copy()
    repo_src = Path(__file__).resolve().parents[2]
    existing = env.get("PYTHONPATH")
    env["PYTHONPATH"] = f"{repo_src}{os.pathsep}{existing}" if existing else str(repo_src)
    return env


def latest_run_dir(base_dir: Path = Path("runs")) -> Path | None:
    """Return the newest run directory containing summary.json."""
    if not base_dir.exists():
        return None
    candidates = [path for path in base_dir.iterdir() if (path / "summary.json").exists()]
    if not candidates:
        return None
    return max(candidates, key=lambda path: path.stat().st_mtime)
