"""Native localhost bench for the existing two-node media-plane runtime."""

from __future__ import annotations

from dataclasses import dataclass, field
import json
import os
from pathlib import Path
import socket
import subprocess
import sys
import time
from typing import Any
from urllib.parse import urlparse

import yaml


DEFAULT_GENERATED_DIR = Path("configs/runs/local/generated")
DEFAULT_LOGS_DIR = Path("runs/local-two-node")
# Los prompt sets viven en el repo hermano experimental-setup (ver spec
# 2026-06-27-experimental-setup-config-design §7). Resuelto relativo al repo del
# media-plane para no depender del CWD.
EXPERIMENTAL_SETUP_PROMPTS = (
    Path(__file__).resolve().parents[3].parent / "e-ovrt_experimental-setup" / "prompts"
)
DEFAULT_ACTIVE_IDS = {
    "cr01_cr02_bench_v2": ["person", "helmet", "vest", "bare_head"],
    "cr01_cr02_v2_short": ["person", "helmet", "vest"],
}
SOURCE_REFS = {
    "bench-val": "bench_v2_val",
    "bench-test": "bench_v2_test",
    "demo": "demo_v2",
}
PROMPTS_BY_SOURCE = {
    "bench-val": "cr01_cr02_bench_v2",
    "bench-test": "cr01_cr02_bench_v2",
    "demo": "cr01_cr02_v2_short",
    "video": "cr01_cr02_v2_short",
    "ezviz": "cr01_cr02_v2_short",
}


@dataclass(frozen=True)
class LocalTwoNodeOptions:
    source: str
    video: Path | None = None
    rtsp_url: str | None = None
    codec: str = "jpeg"
    jpeg_quality: int = 90
    payload_format: str = "uint8_rgb"
    max_units: int | None = None
    device: str = "cuda:0"
    model_ref: str = "yoloe/yoloe-26s"
    prompts_ref: str | None = None
    save_previews: bool = False
    preview_max: int = 20
    generated_dir: Path = DEFAULT_GENERATED_DIR
    logs_dir: Path = DEFAULT_LOGS_DIR
    outputs_base_dir: Path = Path("runs")
    session_dir: Path | None = None
    debug: bool = False
    skip_probe: bool = False
    port_base: int | None = None
    startup_timeout_s: float = 10.0


def _require_supported_source(source: str) -> None:
    supported = {*SOURCE_REFS, "video", "ezviz"}
    if source not in supported:
        choices = ", ".join(sorted(supported))
        raise ValueError(f"--source debe ser uno de: {choices}")


def resolve_source(options: LocalTwoNodeOptions) -> dict[str, Any]:
    """Resolve a user-facing source profile into a run-config source section."""
    _require_supported_source(options.source)
    if options.source in SOURCE_REFS:
        return {"ref": SOURCE_REFS[options.source]}
    if options.source == "video":
        if options.video is None:
            raise ValueError("--source video requiere --video")
        return {"type": "video_file", "path": str(options.video)}
    rtsp_url = options.rtsp_url or os.environ.get("EZVIZ_RTSP_URL")
    if not rtsp_url:
        raise ValueError("--source ezviz requiere --rtsp-url o EZVIZ_RTSP_URL")
    return {
        "type": "rtsp",
        "path": rtsp_url,
        "url": rtsp_url,
        "reconnect_retries": 5,
        "reconnect_delay_ms": 1000,
    }


def resolve_prompts_ref(options: LocalTwoNodeOptions) -> str:
    """Return the prompt set reference for the selected source."""
    if options.prompts_ref:
        return options.prompts_ref
    _require_supported_source(options.source)
    return PROMPTS_BY_SOURCE[options.source]


def build_run_config(
    options: LocalTwoNodeOptions,
    *,
    endpoint: str,
    heartbeat_endpoint: str,
) -> dict[str, Any]:
    """Build the YAML-compatible run config used by both localhost nodes."""
    prompts_ref = resolve_prompts_ref(options)
    raw: dict[str, Any] = {
        "run": {
            "scenario": "EBE",
            "name": f"local_two_node_{options.source.replace('-', '_')}",
            "description": "Native localhost two-node bench generated by run-two-node-local.",
        },
        "source": resolve_source(options),
        "model": {"ref": options.model_ref, "device": options.device},
        "prompts": {
            "file": str(EXPERIMENTAL_SETUP_PROMPTS / f"{prompts_ref}.yaml"),
            "active_ids": DEFAULT_ACTIVE_IDS.get(prompts_ref, ["person", "helmet", "vest"]),
        },
        "topology": {"mode": "two_node"},
        "transport": {
            "backend": "network",
            "endpoint": endpoint,
            "heartbeat_endpoint": heartbeat_endpoint,
            "payload_format": options.payload_format,
            "compression": {"codec": options.codec, "quality": options.jpeg_quality},
        },
        "outputs": {
            "run_dir": str(options.outputs_base_dir),
            "base_dir": str(options.outputs_base_dir),
            "save_previews": options.save_previews,
            "preview_max": options.preview_max,
        },
    }
    if options.max_units is not None:
        raw["run"]["max_units"] = options.max_units
    if options.debug:
        raw["debug"] = {"enabled": True}
    return raw


def write_generated_config(raw: dict[str, Any], generated_dir: Path, *, stem: str) -> Path:
    """Write a generated local run config and return its path."""
    generated_dir.mkdir(parents=True, exist_ok=True)
    path = generated_dir / f"{stem}.yaml"
    path.write_text(yaml.safe_dump(raw, sort_keys=False), encoding="utf-8")
    return path


def unused_tcp_endpoint() -> str:
    """Return a loopback TCP endpoint string for ZeroMQ."""
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
        sock.bind(("127.0.0.1", 0))
        port = sock.getsockname()[1]
    return f"tcp://127.0.0.1:{port}"


@dataclass(frozen=True)
class LocalTwoNodeResult:
    config_path: Path
    logs_dir: Path
    node_a_log: Path
    node_b_log: Path
    run_dir: Path | None
    node_a_returncode: int | None
    node_b_returncode: int | None
    summary: dict[str, Any] = field(default_factory=dict)
    warnings: list[str] = field(default_factory=list)

    @property
    def ok(self) -> bool:
        return self.node_a_returncode == 0 and self.node_b_returncode == 0

    @property
    def failure_reason(self) -> str:
        if self.ok:
            return ""
        if self.node_b_returncode not in (0, None):
            return f"Nodo B exited with code {self.node_b_returncode}"
        if self.node_a_returncode not in (0, None):
            return f"Nodo A exited with code {self.node_a_returncode}"
        return "Two-node local run did not complete"


def _endpoint_host_port(endpoint: str) -> tuple[str, int]:
    parsed = urlparse(endpoint)
    if parsed.scheme != "tcp" or parsed.hostname is None or parsed.port is None:
        raise ValueError(f"Solo endpoints tcp://host:port son soportados: {endpoint}")
    return parsed.hostname, parsed.port


def wait_for_tcp_endpoint(endpoint: str, *, timeout_s: float) -> bool:
    """Wait until a TCP endpoint accepts connections."""
    host, port = _endpoint_host_port(endpoint)
    deadline = time.monotonic() + timeout_s
    while time.monotonic() < deadline:
        try:
            with socket.create_connection((host, port), timeout=0.2):
                return True
        except OSError:
            time.sleep(0.05)
    return False


def scan_log_warnings(log_path: Path) -> list[str]:
    """Return warning/error lines from a node log."""
    if not log_path.exists():
        return []
    matches: list[str] = []
    for line in log_path.read_text(encoding="utf-8", errors="replace").splitlines():
        lowered = line.lower()
        if "warning" in lowered or "error" in lowered or "traceback" in lowered:
            matches.append(line)
    return matches


def collect_run_summary(run_dir: Path | None) -> dict[str, Any]:
    """Read summary.json and count errors.jsonl lines from a completed run."""
    if run_dir is None:
        return {}
    summary_path = run_dir / "summary.json"
    if not summary_path.exists():
        return {}
    summary = json.loads(summary_path.read_text(encoding="utf-8"))
    errors_path = run_dir / "errors.jsonl"
    summary["errors_count"] = (
        len(errors_path.read_text(encoding="utf-8").splitlines())
        if errors_path.exists()
        else 0
    )
    return summary


def resolve_run_dir_from_node_log(log_path: Path, outputs_base_dir: Path) -> Path | None:
    """Resolve this bench run directory from Nodo B's completion log."""
    if not log_path.exists():
        return None
    for line in reversed(log_path.read_text(encoding="utf-8", errors="replace").splitlines()):
        marker = "Corrida completada:"
        if marker not in line:
            continue
        run_id = line.split(marker, 1)[1].strip()
        if not run_id:
            return None
        run_dir = outputs_base_dir / run_id
        return run_dir if run_dir.exists() else None
    return None


def _command_for_node(node: str, config_path: Path) -> list[str]:
    command = "run-producer" if node == "a" else "run-consumer"
    return [sys.executable, "-m", "eovrt_media.cli", command, "--config", str(config_path)]


def _subprocess_env() -> dict[str, str]:
    env = os.environ.copy()
    repo_src = Path(__file__).resolve().parents[2]
    existing = env.get("PYTHONPATH")
    env["PYTHONPATH"] = f"{repo_src}{os.pathsep}{existing}" if existing else str(repo_src)
    return env


def latest_run_dir(base_dir: Path = Path("runs")) -> Path | None:
    """Return the newest run directory containing summary.json."""
    if not base_dir.exists():
        return None
    candidates = [path for path in base_dir.iterdir() if (path / "summary.json").exists()]
    if not candidates:
        return None
    return max(candidates, key=lambda path: path.stat().st_mtime)


def probe_rtsp_config(config_path: Path, *, frames: int = 30) -> None:
    """Probe an RTSP run config using the existing credential-safe probe script."""
    from scripts.probe_rtsp import probe

    probe(config_path, frames=frames)


def _endpoints_for_options(options: LocalTwoNodeOptions) -> tuple[str, str]:
    if options.port_base is not None:
        return (
            f"tcp://127.0.0.1:{options.port_base}",
            f"tcp://127.0.0.1:{options.port_base + 1}",
        )
    return unused_tcp_endpoint(), unused_tcp_endpoint()


def _open_log(path: Path):
    path.parent.mkdir(parents=True, exist_ok=True)
    return path.open("w", encoding="utf-8")


def _terminate_process(process: subprocess.Popen[Any] | None) -> None:
    if process is None or process.poll() is not None:
        return
    process.terminate()
    try:
        process.wait(timeout=5.0)
    except subprocess.TimeoutExpired:
        process.kill()
        process.wait(timeout=5.0)


def run_two_node_local(options: LocalTwoNodeOptions) -> LocalTwoNodeResult:
    """Generate config, launch Nodo A and Nodo B, and collect local bench results."""
    endpoint, heartbeat_endpoint = _endpoints_for_options(options)
    raw_config = build_run_config(
        options,
        endpoint=endpoint,
        heartbeat_endpoint=heartbeat_endpoint,
    )
    config_path = write_generated_config(
        raw_config,
        options.generated_dir,
        stem=f"{options.source.replace('-', '_')}_{options.codec}",
    )

    from eovrt_media.config import load_run_config

    load_run_config(config_path)
    if options.source == "ezviz" and not options.skip_probe:
        probe_rtsp_config(config_path, frames=30)

    session_name = time.strftime("%Y%m%d-%H%M%S")
    logs_dir = options.logs_dir / session_name
    if options.session_dir is not None:
        logs_dir = options.session_dir / "logs" / f"{options.source}_{options.codec}"
    node_a_log = logs_dir / "node-a.log"
    node_b_log = logs_dir / "node-b.log"
    node_a: subprocess.Popen[Any] | None = None
    node_b: subprocess.Popen[Any] | None = None

    from eovrt_media.debugging.events import DebugEventWriter

    debug_writer = DebugEventWriter(logs_dir / "debug_events.jsonl", enabled=options.debug)
    try:
        with _open_log(node_a_log) as node_a_stream, _open_log(node_b_log) as node_b_stream:
            try:
                debug_writer.write(
                    run_id=None,
                    node="session",
                    stage="process",
                    event="process.start",
                    codec=options.codec,
                    extra={"node": "A", "config": str(config_path), "log": str(node_a_log)},
                )
                node_a = subprocess.Popen(
                    _command_for_node("a", config_path),
                    stdout=node_a_stream,
                    stderr=subprocess.STDOUT,
                    cwd=Path.cwd(),
                    env=_subprocess_env(),
                )
                if not wait_for_tcp_endpoint(endpoint, timeout_s=options.startup_timeout_s):
                    _terminate_process(node_a)
                    debug_writer.write(
                        run_id=None,
                        node="session",
                        stage="process",
                        event="process.exit",
                        codec=options.codec,
                        extra={"node": "A", "returncode": node_a.returncode},
                    )
                    return LocalTwoNodeResult(
                        config_path=config_path,
                        logs_dir=logs_dir,
                        node_a_log=node_a_log,
                        node_b_log=node_b_log,
                        run_dir=None,
                        node_a_returncode=node_a.returncode,
                        node_b_returncode=None,
                        summary={},
                        warnings=scan_log_warnings(node_a_log),
                    )

                debug_writer.write(
                    run_id=None,
                    node="session",
                    stage="process",
                    event="process.start",
                    codec=options.codec,
                    extra={"node": "B", "config": str(config_path), "log": str(node_b_log)},
                )
                node_b = subprocess.Popen(
                    _command_for_node("b", config_path),
                    stdout=node_b_stream,
                    stderr=subprocess.STDOUT,
                    cwd=Path.cwd(),
                    env=_subprocess_env(),
                )
                node_b.wait()
                debug_writer.write(
                    run_id=None,
                    node="session",
                    stage="process",
                    event="process.exit",
                    codec=options.codec,
                    extra={"node": "B", "returncode": node_b.returncode},
                )
                node_a.wait(timeout=options.startup_timeout_s)
                debug_writer.write(
                    run_id=None,
                    node="session",
                    stage="process",
                    event="process.exit",
                    codec=options.codec,
                    extra={"node": "A", "returncode": node_a.returncode},
                )
            finally:
                _terminate_process(node_b)
                _terminate_process(node_a)
    finally:
        debug_writer.close()

    node_a_returncode = node_a.returncode if node_a is not None else None
    node_b_returncode = node_b.returncode if node_b is not None else None
    run_dir = resolve_run_dir_from_node_log(node_b_log, options.outputs_base_dir)
    if run_dir is None and node_a_returncode == 0 and node_b_returncode == 0:
        run_dir = latest_run_dir(options.outputs_base_dir)
    warnings = [*scan_log_warnings(node_a_log), *scan_log_warnings(node_b_log)]
    return LocalTwoNodeResult(
        config_path=config_path,
        logs_dir=logs_dir,
        node_a_log=node_a_log,
        node_b_log=node_b_log,
        run_dir=run_dir,
        node_a_returncode=node_a_returncode,
        node_b_returncode=node_b_returncode,
        summary=collect_run_summary(run_dir),
        warnings=warnings,
    )
